name: devops-pipeline

on:
  push:
    branches: [ main ]
env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2    
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'
    - run: npm --prefix frontend install
    - run: npm run --prefix frontend test -- --watchAll=false --coverage=true
    - run: npx --prefix frontend eslint . 
    - run: npm --prefix frontend run build
    - uses: actions/upload-artifact@v2
      with:
        name: deploy
        path: frontend/build
        
  deploy:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/download-artifact@v2
      with:
        name: deploy
        path: frontend/buil
    - run: aws s3 cp frontend/build s3://devops-cyo --recursive --acl public-read
